# <span style="color:red"> QTM 151 - Quiz 3 </span>

## Please submit as an HTML file

<font size = "5" >
This quiz is open book 

- You can use the lecture notes
- You will get partial credit for attempting the questions
- To get full credit, the code should run as intended
- You should <span style="color:red"> NOT </span> communicate with other students

Print the following message: <br>

"I will abide by Emory's code of conduct"

In [1]:
# Write your answer here:

print("I will abide by Emory's code of conduct")

I will abide by Emory's code of conduct

<font size = "5">

Import the libraries "numpy" and "pandas"

In [2]:
import numpy as np 
import pandas as pd


<font size = "5">

(1) Replace values in a column

<font size = "3">

- Load the data from "constructors.csv", assigning it to a DataFrame.
- In the "nationality" column, replace the values "British", "Japanese", and "Irish" with "UK", "Japan", and "Ireland", respectively.
- For full credit, do this by using the ``.replace`` command **one time**

In [6]:
# Your answer here
constructors = pd.read_csv("constructors.csv")
constructors.replace({"nationality":{"British":"UK", "Japnaese":"Japan","Irish":"Ireland"}}, inplace=True)
constructors.head()

,constructorId,constructorRef,name,nationality,url
0,1,mclaren,McLaren,UK,http://en.wikipedia.org/wiki/McLaren
1,2,bmw_sauber,BMW Sauber,German,http://en.wikipedia.org/wiki/BMW_Sauber
2,3,williams,Williams,UK,http://en.wikipedia.org/wiki/Williams_Grand_Pr...
3,4,renault,Renault,French,http://en.wikipedia.org/wiki/Renault_in_Formul...
4,5,toro_rosso,Toro Rosso,Italian,http://en.wikipedia.org/wiki/Scuderia_Toro_Rosso

<font size = "5">

(2) Aggregate and query

<font size = "3">

Import the data from "sprint_results.csv" and assign it to a DataFrame. Do the following:

- Extract the subset corresponding to 'constructorId == 51' using ```.query()```
- Group by the column "driverId", and then aggregate the maximum over the "laps" column for each driver.
- Extract the subset of drivers with maximum of laps $\ge 20$. Assign this to a DataFrame with a name of your choice.

For full credit, perform all the steps in bullet points above in a **single line** using chaining. (If you use line breaks or wrap in parentheses it doesn't literally need to be one line).

**Hint:** I only see your final submission, not the code you wrote along the way. It might be easier to break it up into multiple lines, then combine when you're done.

In [35]:
# Your answer here
sprint_results = pd.read_csv("sprint_results.csv")
sprint_results_agg = sprint_results.query('constructorId==51').groupby('driverId').agg(
    maximum_laps = ("laps", "max")).sort_values('maximum_laps', ascending=False).head(4)

sprint_results_agg

          maximum_laps
driverId
8                   24
822                 24
841                 24
855                 24

<font size = "5">

(3) Recode a numeric column

<font size = "3">

- Import data from "races.csv" and assign it to a DataFrame
- Recode the "year" column into a new column "year_brackets"
with the following categories

$\qquad$ ``` ["1950-1965","1966-1980","1981-onwards"] ```

The easiest method is ``pd.cut()`` but you are not required to use this.

In [39]:
# Your answer here
races = pd.read_csv("races.csv")
df_bins = [1949, 1965, 1980, float("inf")]
df_labels = ["1950-1965", "1966-1980", "1981-onwards"]
races["year_brackets"] = pd.cut(races["year"], 
                                bins = df_bins,
                                right = True,
                                labels = df_labels)
races.head()

,raceId,year,round,circuitId,name,date,time,url,fp1_date,fp1_time,fp2_date,fp2_time,fp3_date,fp3_time,quali_date,quali_time,sprint_date,sprint_time,year_brackets
0,1,2009,1,1,Australian Grand Prix,2009-03-29,06:00:00,http://en.wikipedia.org/wiki/2009_Australian_G...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N,1981-onwards
1,2,2009,2,2,Malaysian Grand Prix,2009-04-05,09:00:00,http://en.wikipedia.org/wiki/2009_Malaysian_Gr...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N,1981-onwards
2,3,2009,3,17,Chinese Grand Prix,2009-04-19,07:00:00,http://en.wikipedia.org/wiki/2009_Chinese_Gran...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N,1981-onwards
3,4,2009,4,3,Bahrain Grand Prix,2009-04-26,12:00:00,http://en.wikipedia.org/wiki/2009_Bahrain_Gran...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N,1981-onwards
4,5,2009,5,4,Spanish Grand Prix,2009-05-10,12:00:00,http://en.wikipedia.org/wiki/2009_Spanish_Gran...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N,1981-onwards

<font size = "5">

(4) Aggregate and sort

<font size = "3">

Import the data from "sprint_results.csv" and assign it to a DataFrame (or use the same DataFrame you created in problem (2)). Do the following:

- Group by "driverId", and then aggregate the average (mean) over the "laps" column.
- Sort the teams by average laps in **descending** order using ``.sort_values()``. Assign this to a DataFrame with a name of your choice.

For full credit, perform both steps in bullet points above in a **single line** using chaining. (If you use line breaks or wrap in parentheses it doesn't literally need to be one line).

**Hint:** Same hint as problem 2. You can chain commands together later.

In [44]:
# Your answer here
sprint_results = pd.read_csv("sprint_results.csv")
sprint_results_agg = sprint_results.groupby('driverId').agg(
    average_laps = ("laps", "mean")
).sort_values("average_laps", ascending=False)
sprint_results_agg

          average_laps
driverId
825          22.666667
1            21.166667
817          21.166667
822          21.166667
839          21.166667
832          21.166667
830          21.166667
840          21.166667
854          21.166667
852          21.166667
849          21.166667
846          21.166667
847          21.166667
844          21.166667
815          21.000000
20           20.833333
8            20.500000
841          19.666667
853          19.666667
848          18.666667
842          18.166667
9            18.000000
4            17.333333
855          15.666667

<font size = "5">

(5) Rename column

<font size = "3">

- Import the data from "sprint_results.csv" and assign it to a DataFrame (or use the same DataFrame you created in problem (2))

- Rename the column "time" to "time_unformatted". The names of the other columns should be left intact.

- Print (or display) the DataFrame to ensure the column was renamed correctly.

In [22]:
# Your answer here
sprint_results = pd.read_csv("sprint_results.csv")
sprint_results.rename(columns={"time":"time_unformatted"}, inplace=True)
print(sprint_results)

     resultId  raceId  driverId  constructorId  number  grid position  \
0           1    1061       830              9      33     2        1
1           2    1061         1            131      44     1        2
2           3    1061       822            131      77     3        3
3           4    1061       844              6      16     4        4
4           5    1061       846              1       4     6        5
..        ...     ...       ...            ...     ...   ...      ...
115       116    1095       840            117      18    15       16
116       117    1095       839            214      31     6       17
117       118    1095         4            214      14     7       18
118       119    1095       849              3       6    16       19
119       120    1095       848              3      23    11       \N

    positionText  positionOrder  points  laps time_unformatted milliseconds  \
0              1              1       3    17        25:38.426      1538426
1              2              2       2    17           +1.430      1539856
2              3              3       1    17           +7.502      1545928
3              4              4       0    17          +11.278      1549704
4              5              5       0    17          +24.111      1562537
..           ...            ...     ...   ...              ...          ...
115           16             16       0    24          +50.700      1862007
116           17             17       0    24          +51.756      1863063
117           18             18       0    24          +53.985      1865292
118           19             19       0    24        +1:16.850      1888157
119            R             20       0    12               \N           \N

    fastestLap fastestLapTime  statusId
0           14       1:30.013         1
1           17       1:29.937         1
2           17       1:29.958         1
3           16       1:30.163         1
4           16       1:30.566         1
..         ...            ...       ...
115          4       1:15.425         1
116          5       1:16.097         1
117          5       1:14.764         1
118          4       1:16.525         1
119          4       1:15.998        31

[120 rows x 16 columns]

<font size = "5">

(6) Merge dataset

<font size = "3">

- Import the data from "sprint_results.csv" and "constructors.csv", assigning them to two DataFrames (you can also re-use the DataFrames you created above.)

- Create a new dataset with  ``pd.merge()``. Treat "sprint_results.csv" as the primary dataset and "constructors.csv" as the secondary dataset. The merge should be based on the column "constructorId".
the column "constructorId"
- To get full credit **ONLY** merge the "nationality" column from the secondary dataset (not all the columns)
- Print (or display) the resulting merged DataFrame to the screen.

**Hint**: Before you start typing "pd.merge(...)" try printing out the two DataFrames you want to merge, excluding any columns that shouldn't be included.

In [40]:
# Your answer here
sprint_results = pd.read_csv("sprint_results.csv")
constructors = pd.read_csv("constructors.csv")
results_merge = pd.merge(sprint_results,
                         constructors[["constructorId", "nationality"]],
                         on = "constructorId",
                         how = "left")

results_merge.head()

,resultId,raceId,driverId,constructorId,number,grid,position,positionText,positionOrder,points,laps,time,milliseconds,fastestLap,fastestLapTime,statusId,nationality
0,1,1061,830,9,33,2,1,1,1,3,17,25:38.426,1538426,14,1:30.013,1,Austrian
1,2,1061,1,131,44,1,2,2,2,2,17,+1.430,1539856,17,1:29.937,1,German
2,3,1061,822,131,77,3,3,3,3,1,17,+7.502,1545928,17,1:29.958,1,German
3,4,1061,844,6,16,4,4,4,4,0,17,+11.278,1549704,16,1:30.163,1,Italian
4,5,1061,846,1,4,6,5,5,5,0,17,+24.111,1562537,16,1:30.566,1,British